"use client";
import {useMemo,useState} from "react";
type Match={home:string;away:string;homeForm:number;awayForm:number;homeGoals:number;awayGoals:number;homeAdv:number};
const matches:Match[]=[
{home:"Arsenal",away:"Chelsea",homeForm:82,awayForm:68,homeGoals:1.9,awayGoals:1.4,homeAdv:7},
{home:"Liverpool",away:"Tottenham",homeForm:79,awayForm:65,homeGoals:2.2,awayGoals:1.5,homeAdv:7},
{home:"Man City",away:"Newcastle",homeForm:84,awayForm:61,homeGoals:2.4,awayGoals:1.2,homeAdv:7}
];
function predict(m:Match){const h=0.5+((m.homeForm-m.awayForm)/100)*0.32+(m.homeGoals-m.awayGoals)*0.08+m.homeAdv/100;const a=0.5-((m.homeForm-m.awayForm)/100)*0.32+(m.awayGoals-m.homeGoals)*0.08;const d=0.26;const raw=[Math.max(.08,h),Math.max(.08,d),Math.max(.08,a)];const s=raw.reduce((x,y)=>x+y,0);return {home:raw[0]/s,draw:raw[1]/s,away:raw[2]/s,score:[Math.max(0,Math.round(m.homeGoals)),Math.max(0,Math.round(m.awayGoals))]}}
export default function Home(){const [i,setI]=useState(0);const [refresh,setRefresh]=useState(0);const m=matches[i];const p=useMemo(()=>predict(m),[m,refresh]);const pct=(x:number)=>Math.round(x*100);return <main><header><div><span className="eyebrow">RAPSOMETTEDY LABS</span><h1>Sports Predictor</h1><p>Football outcome estimates from form, scoring and home advantage.</p></div><button onClick={()=>setRefresh(x=>x+1)}>↻ Refresh</button></header><section className="tabs">{matches.map((x,n)=><button className={n===i?"active":""} onClick={()=>setI(n)} key={x.home}>{x.home}<br/><small>vs {x.away}</small></button>)}</section><section className="card hero"><div className="teams"><span>{m.home}</span><b>VS</b><span>{m.away}</span></div><div className="prediction"><div><strong>{pct(p.home)}%</strong><small>Home</small></div><div><strong>{pct(p.draw)}%</strong><small>Draw</small></div><div><strong>{pct(p.away)}%</strong><small>Away</small></div></div><div className="bar"><i style={{width:p.home*100+"%"}}/><i style={{width:p.draw*100+"%"}}/><i style={{width:p.away*100+"%"}}/></div><div className="result"><span>Model score</span><b>{p.score[0]} – {p.score[1]}</b></div></section><section className="grid"><div className="card"><h2>Model factors</h2><div className="row"><span>Recent form</span><b>{m.homeForm} / {m.awayForm}</b></div><div className="row"><span>Goals / game</span><b>{m.homeGoals} / {m.awayGoals}</b></div><div className="row"><span>Home advantage</span><b>+{m.homeAdv}%</b></div></div><div className="card"><h2>Prediction status</h2><p className="big">{Math.max(p.home,p.draw,p.away)*100|0}%</p><p>Model confidence proxy</p><small>V1 is experimental. It does not guarantee match results.</small></div></section><footer>V1 • Historical/data API integration comes next</footer></main>}